/* IS_AUTOGENERATED_SO_ALLOW_AUTODELETE=YES */
/* The previous line is to allow auto deletion */

#import <Foundation/Foundation.h>
#import <Foundation/NSString.h>
#import "libGolgi.h"



@interface TweetFilter : NSObject
{
    NSString *golgiId;
    BOOL golgiIdIsSet;
    NSString *query;
    BOOL queryIsSet;
}

@property (readonly) BOOL golgiIdIsSet;
- (NSString *)getGolgiId;
- (void)setGolgiId:(NSString *)golgiId;
@property (readonly) BOOL queryIsSet;
- (NSString *)getQuery;
- (void)setQuery:(NSString *)query;

+ (TweetFilter *)deserialiseFromString: (NSString *)string;
+ (TweetFilter *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface TweetDetails : NSObject
{
    NSString *username;
    BOOL usernameIsSet;
    NSString *name;
    BOOL nameIsSet;
    NSData *image;
    BOOL imageIsSet;
    NSInteger timestamp;
    BOOL timestampIsSet;
    NSString *text;
    BOOL textIsSet;
}

@property (readonly) BOOL usernameIsSet;
- (NSString *)getUsername;
- (void)setUsername:(NSString *)username;
@property (readonly) BOOL nameIsSet;
- (NSString *)getName;
- (void)setName:(NSString *)name;
@property (readonly) BOOL imageIsSet;
- (NSData *)getImage;
- (void)setImage:(NSData *)image;
@property (readonly) BOOL timestampIsSet;
- (NSInteger)getTimestamp;
- (void)setTimestamp:(NSInteger )timestamp;
@property (readonly) BOOL textIsSet;
- (NSString *)getText;
- (void)setText:(NSString *)text;

+ (TweetDetails *)deserialiseFromString: (NSString *)string;
+ (TweetDetails *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface TwipWire_stopStreaming_reqArg : NSObject
{
    NSString *golgiId;
    BOOL golgiIdIsSet;
}

@property (readonly) BOOL golgiIdIsSet;
- (NSString *)getGolgiId;
- (void)setGolgiId:(NSString *)golgiId;

+ (TwipWire_stopStreaming_reqArg *)deserialiseFromString: (NSString *)string;
+ (TwipWire_stopStreaming_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface TwipWire_stopStreaming_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (TwipWire_stopStreaming_rspArg *)deserialiseFromString: (NSString *)string;
+ (TwipWire_stopStreaming_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface TwipWire_startStreaming_reqArg : NSObject
{
    TweetFilter *filter;
    BOOL filterIsSet;
}

@property (readonly) BOOL filterIsSet;
- (TweetFilter *)getFilter;
- (void)setFilter:(TweetFilter *)filter;

+ (TwipWire_startStreaming_reqArg *)deserialiseFromString: (NSString *)string;
+ (TwipWire_startStreaming_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface TwipWire_startStreaming_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (TwipWire_startStreaming_rspArg *)deserialiseFromString: (NSString *)string;
+ (TwipWire_startStreaming_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface TwipWire_newTweet_reqArg : NSObject
{
    TweetDetails *tweetDetails;
    BOOL tweetDetailsIsSet;
}

@property (readonly) BOOL tweetDetailsIsSet;
- (TweetDetails *)getTweetDetails;
- (void)setTweetDetails:(TweetDetails *)tweetDetails;

+ (TwipWire_newTweet_reqArg *)deserialiseFromString: (NSString *)string;
+ (TwipWire_newTweet_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface TwipWire_newTweet_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (TwipWire_newTweet_rspArg *)deserialiseFromString: (NSString *)string;
+ (TwipWire_newTweet_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end
//
// stopStreaming
//
@protocol TwipWireStopStreamingResultSender
- (void)success;
@end
@protocol TwipWireStopStreamingResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol TwipWireStopStreamingRequestReceiver
- (void)stopStreamingWithResultSender:(id<TwipWireStopStreamingResultSender>)resultSender andGolgiId:(NSString *)golgiId;
@end

//
// startStreaming
//
@protocol TwipWireStartStreamingResultSender
- (void)success;
@end
@protocol TwipWireStartStreamingResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol TwipWireStartStreamingRequestReceiver
- (void)startStreamingWithResultSender:(id<TwipWireStartStreamingResultSender>)resultSender andFilter:(TweetFilter *)filter;
@end

//
// newTweet
//
@protocol TwipWireNewTweetResultSender
- (void)success;
@end
@protocol TwipWireNewTweetResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol TwipWireNewTweetRequestReceiver
- (void)newTweetWithResultSender:(id<TwipWireNewTweetResultSender>)resultSender andTweetDetails:(TweetDetails *)tweetDetails;
@end

@interface TwipWireSvc : NSObject
+ (void)sendStopStreamingUsingResultReceiver:(id<TwipWireStopStreamingResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withGolgiId:(NSString *)golgiId;
+ (void)sendStopStreamingUsingResultReceiver:(id<TwipWireStopStreamingResultReceiver>)resultReceiver andDestination:(NSString *)_dst withGolgiId:(NSString *)golgiId;
+ (void)registerStopStreamingRequestReceiver:(id<TwipWireStopStreamingRequestReceiver>)requestReceiver;

+ (void)sendStartStreamingUsingResultReceiver:(id<TwipWireStartStreamingResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withFilter:(TweetFilter *)filter;
+ (void)sendStartStreamingUsingResultReceiver:(id<TwipWireStartStreamingResultReceiver>)resultReceiver andDestination:(NSString *)_dst withFilter:(TweetFilter *)filter;
+ (void)registerStartStreamingRequestReceiver:(id<TwipWireStartStreamingRequestReceiver>)requestReceiver;

+ (void)sendNewTweetUsingResultReceiver:(id<TwipWireNewTweetResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withTweetDetails:(TweetDetails *)tweetDetails;
+ (void)sendNewTweetUsingResultReceiver:(id<TwipWireNewTweetResultReceiver>)resultReceiver andDestination:(NSString *)_dst withTweetDetails:(TweetDetails *)tweetDetails;
+ (void)registerNewTweetRequestReceiver:(id<TwipWireNewTweetRequestReceiver>)requestReceiver;

@end
